go back down to 8.10.2 because:
```
[20 of 21] Compiling Data.ListLike.Instances ( src/Data/ListLike/Instances.hs, dist/build/Data/ListLike/Instances.o, dist/build/Data/ListLike/Instances.dyn_o )

src/Data/ListLike/Instances.hs:135:10: error:
    Duplicate instance declarations:
      instance IsList BSC.ByteString
        -- Defined at src/Data/ListLike/Instances.hs:135:10
      instance IsList BSC.ByteString
        -- Defined in ‘Data.ByteString.Internal’
    |
135 | instance IsList BS.ByteString where
    |          ^^^^^^^^^^^^^^^^^^^^

src/Data/ListLike/Instances.hs:258:10: error:
    Duplicate instance declarations:
      instance IsList BSLC.ByteString
        -- Defined at src/Data/ListLike/Instances.hs:258:10
      instance IsList BSLC.ByteString
        -- Defined in ‘Data.ByteString.Lazy.Internal’
    |
258 | instance IsList BSL.ByteString where
```